version: '3.9'

services:
  db:
    image: postgres:14.7-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../skymarket/.env.docker
    restart: always
    expose:
      - '5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ../frontend_react/.
    volumes:
      - frontend:/app/build
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: ../skymarket/.
    command: >
      bash -c "python manage.py collectstatic --noinput
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py loadall
      && python manage.py runserver 0.0.0.0:8001"
    expose:
      - '8001'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/code/staticfiles/
      - media:/code/mediafiles/
      - ../skymarket/.env.docker:/code/.env

  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - "80:80"
    volumes:
      - static:/code/staticfiles/
      - media:/code/mediafiles/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  frontend:
  static:
  media: